{% set version = '0.7.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-iheatmapr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/iheatmapr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iheatmapr/iheatmapr_{{ version }}.tar.gz
  sha256: 1b72ac3cd645ef0ddc31d2c92a659e35d42c94f405f036413775f05dc1dd8db0

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-fastcluster
    - r-ggdendro
    - r-htmlwidgets
    - r-jsonlite
    - r-knitr
    - r-magrittr
    - r-scales
  run:
    - r-base
    - r-rcolorbrewer
    - r-fastcluster
    - r-ggdendro
    - r-htmlwidgets
    - r-jsonlite
    - r-knitr
    - r-magrittr
    - r-scales

test:
  commands:
    - $R -e "library('iheatmapr')"           # [not win]
    - "\"%R%\" -e \"library('iheatmapr')\""  # [win]

about:
  home: https://docs.ropensci.org/iheatmapr/ (website) https://github.com/ropensci/iheatmapr
  license: MIT
  summary: Make complex, interactive heatmaps. 'iheatmapr' includes a modular system for iteratively
    building up complex heatmaps, as well as the iheatmap() function for making relatively
    standard heatmaps.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ctuni

# Package: iheatmapr
# Type: Package
# Title: Interactive, Complex Heatmaps
# Version: 0.7.1
# Authors@R: c(person("Alicia", "Schep", email = "aschep@gmail.com", role = c("aut"), comment = c(ORCID = "orcid.org/0000-0002-3915-0618")), person("Sarah", "Kummerfeld", email = "kummerfeld.sarah@gene.com", role = c("aut"), comment = c(ORCID = "orcid.org/0000-0002-0089-2358")), person("Genentech", role = "cph"), person("Andee", "Kaplan", role = "rev", comment = "Reviewer for rOpensci review process https://github.com/ropensci/onboarding/issues/107"), person("Carl", "Ganz", role = "rev", comment = "Reviewer for rOpensci review process https://github.com/ropensci/onboarding/issues/107"), person("Alex", "Johnson", role = "ctb", comment = "plotly.js library"), person("Etienne", "Tetreault-Pinard", role = "ctb", comment = "plotly.js library"), person("Mikola", "Lysenko", role = "ctb", comment = "plotly.js library"), person("Ricky", "Reusser", role = "ctb", comment = "plotly.js library"), person("Robert", "Monfera", role = "ctb", comment = "plotly.js library"), person("Nicolas", "Riesco", role = "ctb", comment = "plotly.js library"), person("Miklos", "Tusz", role = "ctb", comment = "plotly.js library"), person("Chelsea", "Douglas", role = "ctb", comment = "plotly.js library"), person("Ben", "Postlethwaite", role = "ctb", comment = "plotly.js library"), person("Chris", "Parmer", role = "ctb", comment = "plotly.js library"), person("Alex", "Vados", role = "ctb", comment = "plotly.js library"), person("Plotly", role = "cph", comment = "plotly.js library"), person("Frederick", "Boehm", role = "ctb", comment = "colorbars & main_heatmap"), person("Alan", "O'Callaghan", email = "alan.ocallaghan@outlook.com", role = "cre"))
# Description: Make complex, interactive heatmaps. 'iheatmapr' includes a modular system for iteratively building up complex heatmaps, as well as the iheatmap() function for making relatively standard heatmaps.
# License: MIT + file LICENSE
# Depends: R (>= 3.5.0)
# Imports: methods, utils, magrittr, stats, ggdendro, fastcluster, RColorBrewer, htmlwidgets, jsonlite, scales, knitr, tools
# Suggests: htmltools, datasets, shiny, testthat, rmarkdown, reshape2, roxygen2, covr, webshot
# RoxygenNote: 7.3.1
# VignetteBuilder: knitr
# URL: https://docs.ropensci.org/iheatmapr/ (website) https://github.com/ropensci/iheatmapr
# BugReports: https://github.com/ropensci/iheatmapr/issues
# Encoding: UTF-8
# Collate: 'AllClasses.R' 'AllGenerics.R' 'annotations.R' 'axes.R' 'axis_labels.R' 'axis_titles.R' 'barplot.R' 'clustering.R' 'clusters.R' 'colorbars.R' 'colors.R' 'components.R' 'dendogram.R' 'generic_subplots.R' 'groups.R' 'main_heatmap.R' 'iheatmap.R' 'iheatmapr.R' 'layout.R' 'list_utils.R' 'shiny.R' 'shiny_test.R' 'signal.R' 'subplot.R' 'summary.R' 'to_widget.R' 'utils.R'
# X-schema.org-applicationCategory: Visualization
# X-schema.org-keywords: heatmap, plotly, r, interactive-visualizations, data-visualization, htmlwidgets
# X-schema.org-isPartOf: https://ropensci.org
# Language: en-US
# NeedsCompilation: no
# Packaged: 2024-01-25 23:30:33 UTC; alan
# Author: Alicia Schep [aut] (<https://orcid.org/0000-0002-3915-0618>), Sarah Kummerfeld [aut] (<https://orcid.org/0000-0002-0089-2358>), Genentech [cph], Andee Kaplan [rev] (Reviewer for rOpensci review process https://github.com/ropensci/onboarding/issues/107), Carl Ganz [rev] (Reviewer for rOpensci review process https://github.com/ropensci/onboarding/issues/107), Alex Johnson [ctb] (plotly.js library), Etienne Tetreault-Pinard [ctb] (plotly.js library), Mikola Lysenko [ctb] (plotly.js library), Ricky Reusser [ctb] (plotly.js library), Robert Monfera [ctb] (plotly.js library), Nicolas Riesco [ctb] (plotly.js library), Miklos Tusz [ctb] (plotly.js library), Chelsea Douglas [ctb] (plotly.js library), Ben Postlethwaite [ctb] (plotly.js library), Chris Parmer [ctb] (plotly.js library), Alex Vados [ctb] (plotly.js library), Plotly [cph] (plotly.js library), Frederick Boehm [ctb] (colorbars & main_heatmap), Alan O'Callaghan [cre]
# Maintainer: Alan O'Callaghan <alan.ocallaghan@outlook.com>
# Repository: CRAN
# Date/Publication: 2024-01-25 23:50:02 UTC
